services:
  db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - backend_network

  back-end:
    image: agendasociable/fastapi_app:latest
    build:
      context: ./back-end
      target: dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - cat_name
    networks:
      - backend_network
      - frontend_network

  front-end:
    image: nginx
    container_name: nginx_front
    ports:
      - "8080:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end
    networks:
      - frontend_network

secrets:
  cat_name:
    file: ./secret/cat_name.txt

networks:
  backend_network:
    driver: bridge
    internal: true
  frontend_network:
    driver: bridge