services:
  db:
    build: ./db
    container_name: postgres_db
    ports:
      - "5432:5432"

  back-end:
    build:
      context: ./back-end
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  front-end:
    image: nginx
    container_name: nginx_front
    ports:
      - "8080:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end
